config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/submit_application/:job_id' => 'jobs#submit_application', as: 'submit_application'
  post '/submit_registration/:event_id' => 'events#submit_registration', as: 'submit_registration'

  get '/hosted-jobs' => 'jobs#hosted_jobs', as: 'hosted_jobs'
  get '/hosted-events' => 'events#hosted_events', as: 'hosted_events'

  get '/search', to: 'events#event_search'

  resources :users do
   resources :applications, only: [:index]
   resources :registrations, only: [:index]
   resources :jobs, only: [:new, :create, :show]
   resources :events, only: [:new, :create, :show]
  end

  resources :jobs

  resources :events

  get 'auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

end

app/models/job.rb
class Job < ApplicationRecord
    belongs_to :user
    has_many :job_applications, dependent: :destroy

    scope :posting_date, -> { order('created_at desc') }

    validates :description, presence: :true
    validates :requirements, presence: :true
    validates :compensation, presence: :true
    validates :duration, presence: :true
    validates :schedule, presence: :true
    validates :field_of_work, presence: :true
    validates :contact_info, presence: :true
    validates :location, presence: :true
    validates :employer_name, presence: :true

    def add_application_to_job(applicant)
      JobApplication.create(employer_id: user.id, applicant_id: applicant.id, job_id: id)
    end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:edit, :update, :show, :destroy]
  before_action :edit_own_jobs_only, only: [:edit, :update, :destroy]

    def new
      if params[:user_id]
        @user = User.find_by_id(params[:user_id])
        @job = @user.jobs.build
      else
        @job = Job.new
      end
    end

    def create
      @job = current_user.jobs.build(job_params)

      if @job.save
        flash[:message] = "Job Created Successfully."
        redirect_to job_path(@job)
      else
        flash[:error] = "Unable to Post Job, Please Try Again."
        render :new
      end
    end

    def index
      @hosted_jobs = current_user.jobs
      @job = (Job.all.posting_date) - @hosted_jobs
    end

    def hosted_jobs
      @hosted_jobs = current_user.jobs
    end
      
    def edit
    end

    def update
      if @job.update(job_params)
        flash[:message] = "Job Updated Successfully."
        redirect_to job_path(@job)
      else
        flash[:error] = "Unable to Update Job, Please Try Again."
        render :edit
      end
    end

    def show
    end

    def submit_application
      @job = Job.find(params[:job_id])

      if @job.add_application_to_job(current_user)
        flash[:message] = "Applied For Job Successfully."
        redirect_to job_path(@job)
      else
        flash[:error] = "Unable to Submit Application, Please Try Again."
        redirect_to job_path(@job)
      end
    end

    def destroy
      if @job.destroy
       flash[:message] = "Job Deleted Successfully."
       redirect_to user_path(current_user)
      else
        flash[:error] = "Unable to Delete Job, Please Try Again."
        render :edit
      end
    end

    private

    def set_job
      @job = Job.find_by(id: params[:id])
    end

    def job_params
      params.require(:job).permit(:user_id, :employer_name, :description, :requirements, :compensation, :duration, :schedule, :field_of_work, :contact_info, :name, :location)
    end

    def edit_own_jobs_only
      @job = Job.find_by(id: params[:id])
      current_user.id == @job.user_id
      if current_user.id != @job.user_id
        redirect_to root_path
      end
    end

end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
  <h3>Employer<h3>
  <%= f.text_field :employer_name %>
  <br>
  <br>
  <h3>Job Title<h3>
  <%= f.text_area :name %>
  <br>
  <br>
  <h3>Description</h3>
  <%= f.text_area :description %>
  <br>
  <br>
  <h3>Location</h3>
  <%= f.text_field :location %>
  <br>
  <br>
  <h3>Requirements</h3>
  <%= f.text_area :requirements %>
  <br>
  <br>
  <h3>Compensation</h3>
  <%= f.text_field :compensation %>
  <br>
  <br>
  <h3>Schedule</h3>
  <%= f.text_field :schedule %>
  <br>
  <br>
  <h3>Schedule Type</h3>
  <%= f.select :duration, ['Full-Time/Permanent', 'Part-Time/Permanent', 'Temporary/Contract', 'Internship', 'Apprenticeship']%>
  <br>
  <br>
  <h3>Field of Work</h3>
  <%= f.text_field :field_of_work %>
  <br>
  <br>
  <h3>Contact Info</h3>
  <%= f.text_field :contact_info %>
  <br>
  <br>
  <%= f.submit %>

<% end %>

app/views/jobs/edit.html.erb
<%= render partial: "layouts/errors", locals: {object: @job} %>
<h1>Edit/Delete Job</h1>
<%= render 'form' %>
<%= button_to 'Delete Job', job_path(@job), method: :delete %>

app/views/jobs/hosted_jobs.html.erb
<h2>Hosted Jobs</h2>
<% @hosted_jobs.all.each do |j| %>
<%= link_to j.name, user_job_path(current_user, j) %>
<br>
<br>
<% end %>

app/views/jobs/index.html.erb
<h2>Current Job Openings</h2>
<% Job.all.each do |j| %>
<br>
<br>
<%= link_to j.name, job_path(j) %>
<br>
<br>
Posted at: <%= j.created_at %>
<br>
<% end %>

app/views/jobs/new.html.erb
<%= render partial: "layouts/errors", locals: {object: @job} %>
<h1>Create a Job</h1>
<%= render 'form' %>

app/views/jobs/show.html.erb
<h3>Company</h3>
<%= @job.employer_name %>
<br>
<br>
<h3>Job Title</h3>
<%= @job.name %>
<br>
<br>
<h3>Job Description</h3>
<%= @job.description %>
<br>
<br>
<h3>Requirements</h3>
<%= @job.requirements %>
<br>
<br>
<h3>Compensation</h3>
<%= @job.compensation %>
<br>
<br>
<h3>Schedule</h3>
<%= @job.schedule %>
<br>
<br>
<h3>Schedule Type</h3>
<%= @job.duration %>
<br>
<br>
<h3>Field of Work</h3>
<%= @job.field_of_work %>
<br>
<br>
<h3>Contact Info</h3>
<%= @job.contact_info %>
<br>
<br>
<% if current_user.id == @job.user_id %>
  <%= button_to 'Edit Job', edit_job_path(@job), class: 'btn btn-danger', method: :get %>
  <%= button_to 'Delete Job', job_path(@job), class: 'btn btn-danger', method: :delete %>
  <br>
  <br>

  <h2> Applicants </h2>
  <br>
  <br>
<% @job.job_applications.each do |job_application| %>
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email Address</th>
        <th scope="col">Phone Number</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= job_application.applicant.name %></td>
        <td><%= job_application.applicant.email %></td>
        <td><%= job_application.applicant.phone_number %></td>
      </tr>
    </tbody>
  </table>
  <% end %>

<% else %>

  <% unless current_user.jobs_applied.include?(@job) %>

<%= button_to 'Apply Now', submit_application_path(@job), class: 'btn btn-danger', method: :post %>
  <% end %>
<% end %>

<% if current_user.jobs_applied.include?(@job) %>
<h2>Your application has been submitted. Good Luck!<h2>
<% end %>



<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>