config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/submit_application/:job_id' => 'jobs#submit_application', as: 'submit_application'
  post '/submit_registration/:event_id' => 'events#submit_registration', as: 'submit_registration'

  get '/hosted-jobs' => 'jobs#hosted_jobs', as: 'hosted_jobs'
  get '/hosted-events' => 'events#hosted_events', as: 'hosted_events'

  get '/search', to: 'events#event_search'

  resources :users do
   resources :applications, only: [:index]
   resources :registrations, only: [:index]
   resources :jobs, only: [:new, :create, :show]
   resources :events, only: [:new, :create, :show]
  end

  resources :jobs

  resources :events

  get 'auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    PASSWORD_REQ = /\A 
    (?=.{8,})
    (?=.*\d)
    (?=.*[a-z])
    (?=.*[A-Z])
    (?=.*[[:^alnum:]])
    /x

    validates :email, presence: true, uniqueness: true
    validates :name, presence: true
    validates :password, format: PASSWORD_REQ
    validates :password, confirmation: { case_sensitive: true }

    has_many :jobs
    has_many :events
    has_many :registrations, foreign_key: "attendee_id", class_name: "EventRegistration"
    has_many :hosts, foreign_key: "host_id", class_name: "EventRegistration"
    has_many :employers, foreign_key: "employer_id", class_name: "JobApplication"
    has_many :applications, foreign_key: "applicant_id", class_name: "JobApplication"
    has_many :jobs_applied, through: :applications, source: :job
    has_many :events_registered, through: :registrations, source: :event

    def self.create_with_omniauth(auth)
      user = find_or_create_by(uid: auth['uid'], provider: auth['provider'])
      user.email = "#{auth['uid']}@#{auth['provider']}.com"
      user.password = SecureRandom.hex(8)
      user.name = auth['info']['name']
    
      if User.exists?(user.id)
        user
      else
        user.save!
        user
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :edit_own_profile_only, :only => [:edit, :update]
    
    def new
      @user = User.new
    end

    def create
      @user = User.create(user_params)

      if @user.save
        session[:user_id] = @user.id
        redirect_to @user
      else
        render :new
      end
    end

    def edit
    end

    def update
      @user.update(user_params)
    
      if @user.save
        flash[:message] = "Profile Updated Successfully."
        redirect_to @user
      else
        render :edit
      end
    end

    def show
    end

    private

    def set_user
      @user = User.find_by(id: params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :phone_number, :address, :bio, :resume, :cover_letter)
    end

    def edit_own_profile_only
      @user = User.find_by(id: params[:id])

      current_user.id == @user.id
      if current_user.id != @user.id
        flash[:error] = "You Can Only Edit Your Own Data."
        redirect_to root_path
      end
    end

end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %>
  <br>
  <br>
  <%= f.label :email %>:
  <%= f.email_field :email %>
  <br>
  <br>
  <%= f.label :password %>:
  <%= f.password_field :password %>
  <br>
  <br>
  <%=f.label :password_confirmation %>:
  <%=f.password_field :password_confirmation %>
  <br>
  <br>
  <%= f.label :phone_number %>:
  <%= f.text_field :phone_number %>
  <br>
  <br>
  <%= f.label :address %>:
  <%= f.text_field :address %>
  <br>
  <br>
  <%= f.label :bio %>:
  <%= f.text_area :bio %>
  <br>
  <br>
  <%= f.label :resume %>:
  <%= f.text_area :resume %>
  <br>
  <br>
  <%= f.label :cover_letter %>:
  <%= f.text_area :cover_letter%>
  <br>
  <br>
  <%= f.submit %>

<% end %>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>
<%= render partial: "layouts/errors", locals: {object: @user} %>
<%= render 'form' %>

app/views/users/jobs.html.erb
 <% @user.jobs.each do |f| %>
 <br>
 <%= link_to f.name, job_path(f) %>
 <% end %>

app/views/users/new.html.erb
<%= render partial: "layouts/errors", locals: {object: @user} %>

<h1> Sign-up for an account!</h1>
<%= render 'form' %>
<%= link_to('Create an account using Facebook!', '/auth/facebook') %>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.name %>!</h1>

  
  <%= link_to "Find a Job", jobs_path %>
  <br>
  <%= link_to "Find an Event", events_path %>
  <br>
  <%= link_to "Create a Job", new_user_job_path(current_user) %>
  <br>
  <%= link_to "Create an Event", new_user_event_path(current_user) %>
  <br>
  <%= link_to "Hosted Jobs", hosted_jobs_path %>
  <br>
  <%= link_to "Hosted Events", hosted_events_path  %>
  <br>
  <%= link_to "Active Applications", user_applications_path(@user) %>
  <br>
  <%= link_to "Active Event Registrations", user_registrations_path(@user) %>
  <br>
  <%= link_to "Edit Profile", edit_user_path %>