config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/submit_application/:job_id' => 'jobs#submit_application', as: 'submit_application'
  post '/submit_registration/:event_id' => 'events#submit_registration', as: 'submit_registration'

  get '/hosted-jobs' => 'jobs#hosted_jobs', as: 'hosted_jobs'
  get '/hosted-events' => 'events#hosted_events', as: 'hosted_events'

  get '/search', to: 'events#event_search'

  resources :users do
   resources :applications, only: [:index]
   resources :registrations, only: [:index]
   resources :jobs, only: [:new, :create, :show]
   resources :events, only: [:new, :create, :show]
  end

  resources :jobs

  resources :events

  get 'auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user
    has_many :event_registrations, dependent: :destroy

    scope :posting_date, -> { order('created_at desc') }

    validates :event_time, presence: :true
    validates :name, presence: :true
    validates :description, presence: :true
    validates :agenda, presence: :true
    validates :location, presence: :true
    validates :host_name, presence: :true

    def add_registration_to_event(attendee)
      EventRegistration.create(host_id: user.id, attendee_id: attendee.id, event_id: id)
    end

    def self.search(search)
      if search
        event = Event.where(name: search)
        if event
          event.where(event_id: event)
        else
          Event.all
        end
      else
        Event.all
      end
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update, :show, :destroy]
  before_action :edit_own_events_only, only: [:edit, :update, :destroy]

    def new
      if params[:user_id]
        @user = User.find_by_id(params[:user_id])
        @event = @user.events.build
      else
        @event = Event.new
      end
    end

    def event_search
      @event = Event.search(params[:search])
      render :index
    end

    def create
      @event = current_user.events.build(event_params)
      if @event.save
        flash[:message] = "Event Created Successfully."
        redirect_to event_path(@event)
      else
        flash[:error] = "Unable to Post Event, Please Try Again."
        render :new
      end
    end

    def index
      @event = Event.all.posting_date
    end

    def hosted_events
      @hosted_events = current_user.events
    end

    def edit
    end

    def update
      if @event.update(event_params)
        flash[:message] = "Event Updated Successfully."
        redirect_to event_path(@event)
      else
        flash[:error] = "Unable to Update Event, Please Try Again."
        render :edit
      end
    end

    def show
    end

    def submit_registration
      @event = Event.find(params[:event_id])

      if @event.add_registration_to_event(current_user)
        flash[:message] = "Registered for Event Successfully."
        redirect_to event_path(@event)
      else
        flash[:error] = "Unable to Submit Registration, Please Try Again."
        redirect_to event_path(@event)
      end
    end

    def destroy
      if @event.destroy
        flash[:message] = "Event Deleted Successfully."
        redirect_to user_path(current_user)
      else
        flash[:error] = "Unable to Delete Event, Please Try Again."
        render :edit
      end
    end

    private

    def set_event
      @event = Event.find_by(id: params[:id])
    end

    def event_params
      params.require(:event).permit(:user_id, :host_name, :event_time, :name, :description, :agenda, :location, :id)
    end

    def edit_own_events_only
      @event = Event.find_by(id: params[:id])
      current_user.id == @event.user_id
      if current_user.id != @event.user_id
        flash[:error] = "You Can Only Edit Your Own Events."
        redirect_to root_path
      end
    end

end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>

<%= f.hidden_field(:user_id, :value => @event.user_id)%>

  <h3>Host<h3>
  <%= f.text_area :host_name %>
  <br>
  <br>
  <h3>Name</h3>
  <%= f.text_field :name %>
  <br>
  <br>
  <h3>Event Time</h3>
  <%= f.datetime_field :event_time %>
  <br>
  <br>
  <h3>Location</h3> 
  <%= f.text_field :location %>
  <br>
  <br>
  <h3>Description</h3>
  <%= f.text_area :description %>
  <br>
  <br>
  <h3>Agenda</h3>
  <%= f.text_area :agenda %>
  <br>
  <br>
  <%= f.submit %>

<% end %>

app/views/events/edit.html.erb
<%= render partial: "layouts/errors", locals: {object: @event} %>

<h1>Edit/Delete Event</h1>

<%= render 'form' %>

app/views/events/hosted_events.html.erb
<h2>Hosted Events</h2>

<% @hosted_events.all.each do |j| %>

<%= link_to j.name, user_event_path(current_user, j) %>
<br>
<br>
<% end %>

app/views/events/index.html.erb
<h2>Upcoming Events</h2>

<%= form_tag search_path, method: 'get' do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag ("Search") %>
<% end %>

<% Event.all.each do |e| %>
<br>
<br>
<%= link_to e.name, event_path(e) %>
<br>
<br>
Posted at: <%= e.created_at %>
<% end %>

app/views/events/my_registrations.html.erb
<h2>My Registered Events</h2>

app/views/events/new.html.erb
<%= render partial: "layouts/errors", locals: {object: @event} %>
<h1>Create Event</h1>
<%= render 'form' %>

app/views/events/show.html.erb
<h3>Host</h3>
<%= @event.host_name %>
<br>
<br>
<h3>Event Name</h3>
<%= @event.name %>
<br>
<br>
<h3>Description</h3>
<%= @event.description %>
<br>
<br>
<h3>Agenda</h3>
<%= @event.agenda %>
<br>
<br>
<h3>Event Time</h3>
<%= @event.event_time %>
<br>
<br>
<% if current_user.id == @event.user_id %>
  <%= button_to 'Edit Event', edit_event_path(@event), class: 'btn btn-danger', method: :get %>
  <%= button_to 'Delete Event', event_path(@event), class: 'btn btn-danger', method: :delete %>
  <br>
  <br>

  <h3> Current Registrants </h3>
  <br>
  <br>
  <% @event.event_registrations.each do |event_registration| %>
  <table>
  <tr>
    <th>Name</th>
    <th>Email</th> 
    <th>Phone Number</th>
  </tr>
  <tr>
    <td><%= event_registration.attendee.name %></td>
    <td><%= event_registration.attendee.email %></td>
    <td><%= event_registration.attendee.phone_number %></td>
  </tr>
</table>
   <% end %>

<% else %>

  <% unless current_user.events_registered.include?(@event) %>
  
<%= button_to 'Submit Registration', submit_registration_path(@event), class: 'btn btn-danger', method: :post %>
  <% end %>
<% end %>

<% if current_user.events_registered.include?(@event) %>
<h2>Your registration has been submitted. We'll see you there!<h2>
<% end %>

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>