config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/submit_application/:job_id' => 'jobs#submit_application', as: 'submit_application'
  post '/submit_registration/:event_id' => 'events#submit_registration', as: 'submit_registration'

  get '/hosted-jobs' => 'jobs#hosted_jobs', as: 'hosted_jobs'
  get '/hosted-events' => 'events#hosted_events', as: 'hosted_events'

  get '/search', to: 'events#event_search'

  resources :users do
   resources :applications, only: [:index]
   resources :registrations, only: [:index]
   resources :jobs, only: [:new, :create, :show]
   resources :events, only: [:new, :create, :show]
  end

  resources :jobs

  resources :events

  get 'auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(object.errors.count, "error") %> have occurred:</h2>
  <ul>
  <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobs4Now</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>
  <body>
<div class="navbar navbar-expand-lg" style="background-color: #f5f5e8;">
       <ul class="navbar-nav mr-auto">
         <% if logged_in? %>
         <li class="nav-link">
            <%= link_to "Home", user_path(current_user) %>
            <%= link_to "Logout", logout_path, method:"delete" %>
         </li>
        <% else %>
          <li class="nav-link">
            <%= link_to "Sign Up", new_user_path %>
          </li>
          <li class="nav-link">
            <%= link_to "Log In", login_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
      <div>
        <% if flash[:message] %>
          <%= flash[:message] %>
        <% end %>
        <%= @error %>
      </div>
      <img src='https://i0.wp.com/gamingwithsidekicks.com/wp-content/uploads/2018/01/1369650-white-gradient-background.jpg?fit=1920%2C1080&ssl=1' style='position:fixed;top:0px;left:0px;width:100%;height:100%;z-index:-1;'>
  <div class="container fluid">
    <br>
    
    <%= yield %>
    <br>
  </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>